import java.util.Scanner;
import java.sql.*;

public class Main {

	public static void main(String[] args) throws SQLException {
		//Password and username of the user
		String user_email = "";
		String user_pass =  "";
		
		//Account creation information
		String address, name;
		
		Scanner sc = new Scanner(System.in);
		
		//Create connection to project database (NEED TO PASS CONNECTION TO THE USER/STAFF/NOLOGIN STORE WHEN LAUNCHED)
		//URL and login info for the database access
		String url = "jdbc:mysql://localhost:3306/project";
		String username = "root";
		String password = "root";
		
		Connection con = DriverManager.getConnection(url, username, password);
		//if no exception is thrown than connection successful
		int choice = 0;
		while(choice != 4){
			System.out.println("============================================================================");
			System.out.println("=   #####  #      #   #  #          #####  ######   #####   #####   #####  =");
			System.out.println("=      #   ##     #   #  ##        #          #    #     #  #    #  #      =");
			System.out.println("=      #   # #    #   #  # #        ####      #    #     #  #  ##   ####   =");
			System.out.println("=  #   #   ####    # #   ####           #     #    #     #  #   #   #      =");
			System.out.println("=   ###    #   #    #    #   #     #####      #     #####   #    #  #####  =");
			System.out.println("============================================================================\n");
			
			
			System.out.println("1) Login.");
			System.out.println("2) Create new account.");
			System.out.println("3) View products.");
			System.out.println("4) Exit Store.");
			choice = sc.nextInt();
			boolean badLogin = true;
	
			if(choice == 1){
				while(badLogin){
					System.out.println("Please enter login information.");
					System.out.print("Email: ");
					user_email = sc.next();
					System.out.print("Password: ");
					user_pass = sc.next();
					
					if(checkLogin(con, user_email, user_pass)){
						badLogin = false;
					}
					else{
						System.out.println("Incorrect login information, please try again.\n");
					}
				}
				if(checkStaff(con, user_email, user_pass)){
					loadView(true, user_email, user_pass, con);
				}
				else{
					loadView(false, user_email, user_pass, con);
				}
			}
			else if (choice == 2){
				//clear scanner first
				sc.nextLine();
				boolean isUniqueEmail = false;
				
				//This loops until a unique email address is provided for the account
				//Can't have two accounts with the same email address
				while(!isUniqueEmail){
					System.out.println("Please enter info to create your account.");
					System.out.print("Email: ");
					user_email = sc.nextLine();
					if(checkEmail(user_email, con)){
						isUniqueEmail = true;
					}
					else{
						System.out.print("Email already in use please enter a different one.");
					}
				}
				
				System.out.print("Password: ");
				user_pass = sc.nextLine();
				//sc.nextLine();
				System.out.print("Name: ");
				name = sc.nextLine();
				System.out.print("Address: ");
				address = sc.nextLine();
				
				createAccount(con, user_email, user_pass, name, address);
			}
			else if (choice == 3){
				NoLoginStore ns = new NoLoginStore(con);
				
				//LOADING ANIMATION
				String loading = "Loading Store...";
				for(int i = 0; i < loading.length(); i++){
					char c = loading.charAt(i);
					System.out.print(c);
					try {Thread.sleep(120);} catch (InterruptedException e) {}
				}
				System.out.print("\n");
				//LOADING ANIMATION
				
				ns.start();
			}
			else{
				System.out.println("Goodbye!");
			}
		}
	}
	
	public static void createAccount(Connection con, String email, String pass, String name, String address){
		//accounts created thorough the program are user only, staff accounts must be added manually		
		//put the user info into the database (id auto generated by database)
		
		Statement stmt = null;
	    String insert = "INSERT INTO project.user (address, name, password, email, is_staff) " + 
	    				"VALUES ('" + address + "', '" + name + "', '" + pass + "', '" + email + "', 'n')";

	    try {
	        stmt = con.createStatement();
	        stmt.executeUpdate(insert);
	        //if successful no error is thrown
	    } catch (SQLException e ) {
	    	e.printStackTrace();
	    } finally {
	        if (stmt != null) { 
	        	try { stmt.close();} catch (SQLException e) {} 
	        }
	    }
		
		System.out.println("Congradulations your account has been successfully created.");
		loadView(false, email, pass, con);
	}
	
	public static boolean checkLogin(Connection con, String email, String pass){
		//check user table to see if the login exists,
		Statement stmt = null;
	    String query = "SELECT email " +
	                   "FROM project.user " +
	                   "WHERE email = '" + email + "' AND password = '" + pass + "'";
	    try {
	        stmt = con.createStatement();
	        ResultSet rs = stmt.executeQuery(query);
	        //If query returns no results than the account does not exist
	        if(!rs.next()){  
	        	return false;
	        }

	    } catch (SQLException e ) {
	    	e.printStackTrace();
	    } finally {
	        if (stmt != null) { 
	        	try { stmt.close();} catch (SQLException e) {} 
	        }
	    }
	    
		return true;
	}
	
	public static boolean checkStaff(Connection con, String email, String pass){
		//check user table to see if staff member
		String isStaff = "";
		Statement stmt = null;
	    String query = "SELECT is_staff " +
	                   "FROM project.user " +
	                   "WHERE email = '" + email + "' AND password = '" + pass + "'";
	    try {
	        stmt = con.createStatement();
	        ResultSet rs = stmt.executeQuery(query);
	        while (rs.next()) {
	        	isStaff = rs.getString("is_staff");
	        }
	        
	    } catch (SQLException e ) {
	    	e.printStackTrace();
	    } finally {
	        if (stmt != null) { 
	        	try { stmt.close();} catch (SQLException e) {}
	        }
	    }
	    //If they are staff return true
	    if(isStaff.charAt(0) == 'y'){
        	return true;
        }
	    //else return false
		return false;
	}
	
	public static void loadView(boolean isStaff, String user_email, String user_pass, Connection con){
		
		//LOADING ANIMATON
		String loading = "Loading Store...";
		for(int i = 0; i < loading.length(); i++){
			char c = loading.charAt(i);
			System.out.print(c);
			try {Thread.sleep(120);} catch (InterruptedException e) {}
		}
		System.out.print("\n");
		//LOADING ANIMATION
		
		if(isStaff){
			StaffStore ss = new StaffStore(con);
			ss.start(user_email, user_pass);
		}
		else{
			UserStore us = new UserStore(con);
			us.start(user_email, user_pass);
		}
	}
	
	public static boolean checkEmail(String email, Connection con){
		//check user table to see if the given email is already in use
		Statement stmt = null;
	    String query = "SELECT email " +
	                   "FROM project.user " +
	                   "WHERE email = '" + email + "'";
	    try {
	        stmt = con.createStatement();
	        ResultSet rs = stmt.executeQuery(query);
	        //If query returns no results than the account does not exist
	        if(!rs.next()){  
	        	return true;
	        }

	    } catch (SQLException e ) {
	    	e.printStackTrace();
	    } finally {
	        if (stmt != null) { 
	        	try { stmt.close();} catch (SQLException e) {} 
	        }
	    }
	    
		return false;
	}
}
